sudo: required
services:
  - docker

before_install:
  - docker build -t dorbecker2684/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true dorbecker2684/react-test npm test

after_success:
  - docker build -t dorbecker2684/multi-client ./client
  - docker build -t dorbecker2684/multi-nginx ./nginx
  - docker build -t dorbecker2684/multi-server ./server
  - docker build -t dorbecker2684/multi-worker ./worker
  #Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and put into docker hub
  - docker push dorbecker2684/multi-client
  - docker push dorbecker2684/multi-nginx
  - docker push dorbecker2684/multi-server
  - docker push dorbecker2684/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-039667219069
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
